### ISSUE TITLE
Need Help Whit Schulk

### ISSUE THREAD

**Issue by J35U59** [Alshanex/OriginsOverhaul#3]
Every time I enter into my world as a schulk they give me the same four books and i have infinite copies of them, i know that those are my powers as a schulk but i dont need so many copies of it idk, is that the way it is or its a bug?

**Comment by Alshanex** [comment]
Sorry but i don't really know what are you talking about.
This mod doesn't add any books so i can't really tell what's happening there.

**Comment by J35U59** [comment]
Really? there is a few books that appears anytime i enter my survival world and they not appear in creative mode, i though that it was this mod because it start apeearing when i install it
![IMG_20241119_185748_552](https://github.com/user-attachments/assets/386908aa-c16a-418e-b729-150ffe655b78)
![IMG_20241119_185737_180](https://github.com/user-attachments/assets/7dd6c2bd-d753-436b-8d5e-585db9d775c7)
This are the books

**Comment by Alshanex** [comment]
Sorry but that's not from this mod, i can't help with that.
