### ISSUE TITLE
Eldritch Ghoul

### ISSUE THREAD

**Issue by OgKawaiii** [Alshanex/OriginsOverhaul#4]
So as the description of the Origin class says that if i have 50 souls i can right click a ancient city portal and recieve an upgrade that i can do up to 4 times and I have tried every kind of soul that is in that mod and it just doesnt work

**Comment by Alshanex** [comment]
The soul indicator is the blue bar at the top right of your hotbar, when you fill It up entirely you can go exchange them for the upgrades.
